---
title: "Data_Visualization_ggplot2"
author: "Reinp"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: 
    keep_md: yes
  word_document: default
---

# R Programming

## Set Chunk requirements

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
#echo=FALSE indicates that the code will not be shown in the final document 
#(though any results/output would still be displayed).
#include=FALSE to have the chunk evaluated, but neither the code nor its output displayed
# warning=FALSE and message=FALSE suppress any R warnings or messages from being included 
#in the final document
```

Load Relevant Packages and Data Set

```{r}
setwd('E:/Documents/Reinp/GitHub Respositories/ggplot2_package')

library(tidyverse)
## tidyverse includes readr, ggplot2, dplyr, forcats, tibble, tidyr, purrr, stringr

data("iris") #load Datasets distributed with R
View(iris)

iris

head(iris)

tail(iris)

# How many variables and observations are there?
ncol(iris)

nrow(iris)

#learn more about the dataset
help(iris)
??iris
str(iris)
class(iris)
typeof(iris) 
length(iris)
names(iris) #display variable names
#attributes(iris) #names(iris), class(iris), row.names(iris)

#ggplot2::geom

```


## Scatter/Dot plots

```{r}

ggplot(data = iris, 
       mapping = aes(x = Sepal.Length,
                     y = Petal.Length,
                    )) + geom_point()

## Compared to base R scatter plot
plot(Petal.Length~Sepal.Length, data = iris)


### Now adding some colour to the scatter plot 

ggplot(iris, 
       aes(x = Sepal.Length,
           y = Petal.Length,
           colour = Species)) + 
  geom_point()

### Making both the colour and shape based on Species
ggplot(iris,
       aes(x = Sepal.Length, 
           y = Petal.Length, 
           colour = Species, 
           shape = Species)) + geom_point()
```

## Histograms

```{r}
### Making a histogram of petal lengths
ggplot(data = iris,
       mapping = aes(x = Petal.Length)) +
  geom_histogram(fill = "lightblue", colour = "black")


ggplot(data = iris,
       mapping = aes(x = Petal.Length
                     )) + 
  geom_histogram(fill = "blue", colour = "black")


### Using species with histogram fill
ggplot(data = iris,
       mapping = aes(x = Petal.Length,
                     fill = Species)) + 
  geom_histogram(colour = "black")

### Using position as identity
ggplot(data = iris, 
       mapping = aes(x = Petal.Length,
                     fill = Species)) + 
  geom_histogram(position = "identity", colour = "black", 
                 alpha = 0.4)

#changing the default stacking of groups and adding transparency

ggplot(data = iris, 
       aes(x = Petal.Length, 
           fill = Species)) + geom_histogram(position = "identity",
                                             alpha = 0.6)

ggplot(data = iris,
       mapping = aes(x = Petal.Length,
                     fill = Species)) + 
  geom_density(alpha = 0.5) 

mean(iris$Petal.Length)
sd(iris$Petal.Length)


```

## Box Plots

```{r}

### Making a box plot to compare petal lengths of different species

ggplot(data = iris,
       aes(x = Species,
           y = Petal.Length)) + 
  geom_boxplot()

### Violin plot 

ggplot(data = iris,
       aes(x = Species, 
          y = Petal.Length)) + 
  geom_violin()
```

## Bargraphs

### Bar graphs with counts

```{r}

nyc311 <- read_csv("data/nyc311_Jan-March2020.csv")


### Which borough has the most complaints?

## base R 
table(nyc311$Borough)

## USing dplyr
count(nyc311, Borough, sort = TRUE)


### How to make a bar chart
## data: nyc311
## aesthetic: x: Borough, 

ggplot(data = nyc311, 
       aes(x = Borough)
       ) + geom_bar() 

library(scales) #to get the comma label 

ggplot(data = nyc311, 
       aes(x = Borough)) +
  geom_bar(fill = "royalblue") + scale_y_continuous(label = comma)


### Which agencies get the most complaints?

ggplot(data = nyc311,
       aes(x = Agency)) + 
  geom_bar(fill = "blue") + scale_y_continuous(label = comma) +
  coord_flip()


## fct_lump is in the forcats package - for dealing with factors which is included in the tidyverse 

nyc311_fct_lump <- mutate(nyc311, Agency2 = fct_lump(Agency, 5))

ggplot(data = nyc311_fct_lump,
       aes(x = Agency2)) +
  geom_bar(fill = "blue") + scale_y_continuous(label = comma)

```

### Bar graphs with totals Part 1

```{r}
chicago <- read_csv("data/ChicagoEmployees2020.csv")
chicago <- mutate(chicago, Dept = fct_lump(Department, 4)) 

count(chicago, Dept)

### bar chart of number of employees
ggplot(data = chicago, 
       aes(x = Dept)) + geom_bar()  #  stat = "count" for the default value

ggplot(data = chicago, 
       aes(x = Dept, y = AnnSalary)) + geom_bar(stat = "identity") + 
  ggtitle("Annual Salaries of Chicago Employees") + xlab("Department") + 
  ylab("Total Salaries") + 
  theme(plot.title = element_text(size = 16, face = "bold", color = "red", hjust = 0.5))

ggplot(data = chicago,
       aes(x = Dept, y = AnnSalary)) + geom_col()

ggplot(data = chicago,
       aes(x = Dept,  y = AnnSalary)) + stat_identity(shape = 21) 

```


### Bar graphs with totals Part 2

```{r}
df <- read_csv("data/wafanyikazi.csv")

##Generate summary statistics table
tab1 <- df %>% 
  group_by(Gender) %>% 
  summarize(count = n()) %>% 
  mutate(percentage = round(count/sum(count)*100,0))  
##Set theme in advance
mytheme <-  theme(plot.title = element_text(face = "bold", hjust = 0.5, vjust = -0.25,size = 14),
                axis.title = element_text(face = "italic", size = 12),
                axis.text = element_text(face = 12),
                axis.line = element_line(size = 1.5),
                plot.subtitle = element_text(hjust = 0.5,size = 12),
                plot.caption = element_text(face = "bold",size = 12),
                panel.background = element_rect(fill = NA))

##Generate bar graph
  
  bargraph1 <- ggplot(data = tab1,aes(x = Gender,y = percentage)) +
               geom_bar(stat = "identity",fill = "brown") +
               geom_text(aes(label = paste0(percentage,"%")),hjust = 0.5,vjust = -0.25)+
               mytheme+
               
               labs(title = "Gender distribution",
                    x = "Gender",
                    y = "percentage")
  bargraph1
  
 ##Generate summary statistcs for department
  
  tab2 <- df %>% 
    group_by(Department) %>% 
    summarise(count =n()) 
    
  bargraph2 <- ggplot(data = tab2,aes(x = reorder(Department,-count),y = count))+
               geom_bar(stat = "identity",fill = "blue")+
               geom_text(aes(label = count,hjust = 0.5, vjust = -0.25))+
               mytheme+
               labs(title = "Distribution of department",
                    x = "Department",
                    y = "count")
  bargraph2
##Summary statistics for marital status  
  tab3 <- df %>% 
    group_by(Marital_Status) %>% 
    summarise(count = n()) %>% 
    mutate(percentage = round(count/sum(count)*100,0))
  
  ##Bar graph for marital status
  bargraph3 <- ggplot(data = tab3,aes(x = Marital_Status, y = percentage)) +
               geom_bar(stat ="identity", fill = "red")+
               geom_text(aes(label = paste0(percentage,"%"), hjust = 0.5, vjust = -0.25))+
               mytheme+
               labs(title = "Distribution of Marital status",
                    x = "Marital status",
                    y = "percentage")
  bargraph3
  
  #plotting bargraph for more than one variable
  ## Summary statistics for department and role
  tab4 <- df %>% 
    group_by(Department,Role) %>% 
    summarise(count = n()) %>% 
    mutate(percentage = round(count/sum(count)*100,0))
  ##Bar graph for department and role
  
  bargraph4 <- ggplot(data = tab4, aes(x = Department, y = percentage, fill = Role))+
               geom_bar(stat = "identity",position = "dodge")+
               geom_text(aes(label = percentage),hjust = 0.5,vjust = 0.25,size =4,
                          position = position_dodge(width = 0.9))+
               mytheme+
              theme(axis.text.x = element_text(angle = 90))+
  
               scale_fill_manual(values = c("pink","blue","maroon"))+
               labs(title = "Distribution\n of\n Department\n per role", 
                          x = "Department",y = "percentage")+
              facet_wrap(~Role, ncol = 3)
  bargraph4
  
  ##Bar graph to show age category vs gender
  ####Create age categories
  tab5 <- df %>% 
       mutate(age_cat = if_else(Age >=18 & Age <= 24,"Young",
                                if_else(Age >25 & Age <= 35, "middle_age","Old_aged"))) %>% 
       group_by(age_cat,Gender) %>% 
       summarize(count = n()) %>% 
       mutate(perc = round(count/sum(count)*100,0))
  ##Bar graph
   bargraph5 <- ggplot(data = tab5, aes(x = age_cat, y = perc, fill = Gender))+
                geom_bar(stat = "identity", position = "stack")+
                geom_text(aes(label = paste0(perc,"%"), hjust = 0.5, vjust = 0))+
                mytheme+
                scale_fill_manual(values = c("orange","grey"))+
     labs(title = "Distiution of age categories and gender",
             x = "Age category",y = "Percentage")
   bargraph5
 ##Generate bar graph for Marital status and gender distribution   
                     
  tab5 <- df %>% 
    group_by(Marital_Status,Gender) %>% 
    summarize(count = n()) %>% 
    mutate(percentage = round(count/sum(count)*100,0))
  
  bargraph6 <- ggplot(data = tab5, aes(x = Marital_Status, y = percentage, fill = Gender))+
              geom_bar(stat = "identity",position = "dodge")+
              geom_text(aes(label = percentage),hjust = 0.5,vjust = -0.25,
                        position = position_dodge(width = 1.0))+
    mytheme+
      scale_fill_manual(values = c("green","red"))+
    labs(title = "Distribution of Marital status per gender",
         x = "Marital status",
         y ="percentage")
  bargraph6


```


## Line graphs

```{r}

str(nyc311_fct_lump)

library(lubridate)

nyc311_2 <- mutate(nyc311_fct_lump, datetime = mdy_hms(`Created Date`),
                 day = as_date(datetime),
                 weekday = weekdays(day))

grouped_data <- group_by(nyc311_2, day, Agency2) #groups the data frame by day and agency
report <- summarise(grouped_data, Calls = n())

### Make a line graph
ggplot(data = report, aes(x = day, 
                          y = Calls,
                          group = Agency2,
                          colour = Agency2)) +
  geom_line()


### We can facet 
ggplot(data = report, aes(x = day, y = Calls)) +
  geom_line() + facet_wrap(~Agency2, ncol = 2) + theme_bw()


grouped_agencyboro <- group_by(nyc311_2, day, Agency2, Borough)
report2 <- summarise(grouped_agencyboro, Calls = n())

ggplot(data = report2, 
       aes(x = day, y = Calls)) + 
  geom_line() + facet_grid(Agency2~Borough) + 
  theme_bw()

```











